server:
  port: 8042
spring:
  application:
    name: car-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 #配置采样率 默认的采样比例为: 0.1，即 10%，所设置的值介于 0 到 1 之间，1 则表示全部采集
        rate: 10
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
