server:
  port: 8762
spring:
    application:
      name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eurake,http://peer3:8763/eureka
  instance:
    hostname: peer2 # ??????
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # ?? id
    prefer-ip-address: true # ????? ip ?????
    lease-renewal-interval-in-seconds: 10 # ?? eureka client ????? server ????
    lease-expiration-duration-in-seconds: 20 #?? eureka server ?????? client ?????????????????
  #    ?????????????????????????
