server:
  port: 8082
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defalutZone: http://peer1:8761/eureka

#provider:
#    ribbon:
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
