server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
 client:
#   service-url: #eureka ????????????,???,??
#      defaultZone: http://peer1:8761/eureka   #http://peer2:8762/eureka,http://peer3:8763/eureka,
   fetch-registry: true #????????
   register-with-eureka: true #????????? eureka ????????,???????
 server:
  eviction-interval-timer-in-ms: 30000 #?????????(??)--????
  enable-self-preservation: true #server ?????????????????????,????????
  renewal-percent-threshold: 0.85 #85%????????? client ??15 ???? 85%? client
                                 #   ?????????????????????????????????????????????????????
 instance:
  hostname: peer1 #??????
  instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # ?? id
  prefer-ip-address: true # ????? ip ?????
  lease-renewal-interval-in-seconds: 10 # ?? eureka client ????? server ????
  lease-expiration-duration-in-seconds: 20 #?? eureka server ?????? client ?????????????????
#    ?????????????????????????